sonar.projectKey=Portfolio
sonar.projectName=Portfolio
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,.astro/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=false
sonar.scanner.useCache=true
sonar.scanner.connectTimeout=30000
sonar.scanner.socketTimeout=60000
