sonar.projectKey=Portfolio
sonar.projectName=Portfolio
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,.astro/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=false
