name: Sonarqube Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Sonarqube Scan
    runs-on: portfolio-runner

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0

      - name: Sonarqube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
