name: Sonarqube Check
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Sonarqube Scan
    runs-on: selfhosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Sonarqube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 15
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
