name: Sonarqube Check

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Sonarqube Scan
    runs-on: self-hosted

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v5.0.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 17

      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_SCANNER_OPTS: "-Dsonar.scanner.skipJreProvisioning=true"

      - name: Sonarqube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
